[project]
name = "migratube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google>=3.0.0",
    "google-api-python-client>=2.171.0",
    "google-auth>=2.40.3",
    "google-auth-oauthlib>=1.2.2",
]
